### ISSUE TITLE
#Request 

### ISSUE THREAD

**Issue by AllisonOfTg** [Aadhi000/Ajax-Extra-Features#1]
Hello Bro Plzz A dedicated command for the help & about section. Eg /help, /about etc.... It would be a great if u add it

**Comment by Aadhi000** [comment]
Will Try To Add Bro...🙂

**Comment by Aadhi000** [comment]
> Hello Bro Plzz A dedicated command for the help & about section. Eg /help, /about etc.... It would be a great if u add it

Will Try To Add Bro...🙂

**Comment by AllisonOfTg** [comment]
> > Hello Bro Plzz A dedicated command for the help & about section. Eg /help, /about etc.... It would be a great if u add it
> 
> Will Try To Add Bro...🙂

Okey Bro

**Comment by 200920082007** [comment]
Done added /help @AllisonOfTg

**Comment by AllisonOfTg** [comment]
> Done added /help @AllisonOfTg

Thanks bro
